name: Build Database Update
on:
  push:
    paths:
    - '.github/workflows/*'
  workflow_dispatch:
  schedule:
    - cron:  '15 8 * * *'

jobs:
  build_and_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        sudo apt-get install ipcalc
    - name: Downloading CF IP list
      run: |
        curl https://www.cloudflare.com/ips-v4 > /tmp/cf.lsv
    - name: Build list
      run: |
        perl ./helpers/cleanup.pl /tmp/cf.lsv > ipv4.txt
    - name: Push Output of ipv4.txt
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        source_file: 'ipv4.txt'
        destination_repo: '${{ github.repository }}'
        destination_folder: '/'
        user_email: 'automated@x4b.net'
        user_name: 'listbuilder'
        destination_branch: "main"

